services:
  fan-control:
    container_name: fan-control
    build:
      context: .
      dockerfile: Dockerfile
    image: fan-control:latest
    privileged: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/ipmi0:/dev/ipmi0
    volumes:
      - $APPDIR/fan-control/config.yaml:/config/config.yaml:ro
      - /sys:/sys:ro
      - /dev:/dev:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: $TZ
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "managed=true"

networks:
  t2_proxy:
    external: true
